FROM alpine:latest as builder

RUN apk add --no-cache --virtual .build-deps bash gcc musl-dev openssl tar libc-dev

RUN wget https://dl.google.com/go/go1.24.1.linux-arm64.tar.gz
RUN tar -C /usr/local -xzf go1.24.1.linux-arm64.tar.gz
ENV PATH=$PATH:/usr/local/go/bin

WORKDIR /app
COPY . .
RUN go build -o build/

FROM alpine:latest as runner

WORKDIR /app
COPY --from=builder /app/build/ .

CMD [ "./backendTest" ]
